# Generated by Django 6.0.6 on 2026-07-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_clicker_app', '0002_pendingclick_alter_click_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
    ]
